apiVersion: v1
kind: Pod
metadata:
  name: production-webapp
  labels:
    app: development
    tier: production
spec:
  containers:
  - name: production-app
    image: kodekloud/webapp-delayed-start
    ports:
      - containerPort: 8080
        protocol: TCP
    env:
    - name: APP_START_DELAY
      value: "60"
    livenessProbe:
      httpGet:
        path: /live
        port: 8080
      initialDelaySeconds: 70
      periodSeconds: 2
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080

